name: OSS

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deply To OSS
        uses: manyuanrong/setup-ossutil@v1.0
        with:
          endpoint: "oss-cn-shanghai.aliyuncs.com"
          access-key-id: ${{ secrets.ALI_SECRET_ID }}
          access-key-secret: ${{ secrets.ALI_SECRET_KEY }}

      - run: ossutil cp -rf test.txt oss://bucket/path